GRANT ALL PRIVILEGES ON restaurants TO PUBLIC;
GRANT ALL PRIVILEGES ON restaurants_id_seq TO PUBLIC;
GRANT ALL PRIVILEGES ON users TO PUBLIC;
GRANT ALL PRIVILEGES ON users_id_seq TO PUBLIC;
GRANT ALL PRIVILEGES ON waitlists TO PUBLIC;
GRANT ALL PRIVILEGES ON waitlists_id_seq TO PUBLIC;
GRANT ALL PRIVILEGES ON waitlist_entries TO PUBLIC;
GRANT ALL PRIVILEGES ON waitlist_entries_id_seq TO PUBLIC;
